### ISSUE TITLE
RIO.Process is running an "original" instead of a symbolic link

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/rio#217] opened 2020-04-26 20:22 UTC
I'm not fully sure what's happening here, the same codebase started behaving differently once I've reinstalled my Ubuntu from 18.04 to 20.04 but maybe that's unrelated.

I'm using `RIO.Process` to run my python subprocess. The python I'm trying to run is located in virtualenv:

```
$ ls -lah /home/kb/workspace/emotive_conjugations/venv/bin/python
lrwxrwxrwx 1 kb kb 16 Apr 25 23:23 /home/kb/workspace/emotive_conjugations/venv/bin/python -> /usr/bin/python3
```

Once I'm running that python, I get an error, because what it actually does is it ends up running `/usr/bin/python3` instead, because it's calling the `findExecutable` to resolve the name internally:

```
λ RIO.Prelude.Simple.runSimpleApp (RIO.Process.findExecutable "/home/kb/workspace/emotive_conjugations/venv/bin/python")
Right "/usr/bin/python3.8"
```

So, my question is, who is wrong here and how should I call a virtualenv'ed python executable properly? Thanks!

**Comment by snoyberg** [comment] 2020-04-27 04:51
What happens if you give it an absolute path in the first place?

**Comment by k-bx** [comment] 2020-04-27 08:00
@snoyberg all right, I've created a minimal self-containing repo. I also confirm that the code works on macOS, but not Ubuntu 20.04, and suspect it might work fine on Ubuntu 18.04, which might be somewhat alarming https://github.com/k-bx/rio-process-symlink-issue

The README captures the build and run instructions

**Comment by snoyberg** [comment] 2020-04-27 16:50
Does this reproduce with the `process` package?

**Comment by k-bx** [comment] 2020-04-27 19:29
Yes, I rewrote it using the `UnliftIO.Process` and it works now

**Comment by snoyberg** [comment] 2020-04-28 07:24
I'm quite confused about the claim that this works on macOS and Ubuntu 18.04 but not Ubuntu 20.04. I _think_ I know what the problem is: usage of `canonicalizePath` instead of `makeAbsolute` in `findExecutable`. However, that functions behaves identically on macOS and Ubuntu 18.04: resolving symbolic links.

The repro you've provided isn't really minimal, since it depends on assumptions of virtualenv working identically across all OSes and versions. I'm fairly certain that's the problem here. My recommendation: can you try replacing `canonicalizePath` with `makeAbsolute` in the codebase and see if that solves the problem you're seeing?

**Comment by snoyberg** [comment] 2020-04-28 07:41
I don't see a downside to the change, so I've opened #218.

**Comment by k-bx** [comment] 2020-04-28 08:47
@snoyberg yes, tested with the patched rio, it works now. Thank you!

**Closed** 2020-04-28 08:48 UTC
